# File: render.yaml
services:
  - type: web
    name: histoscan-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --threads 2 --worker-class sync app:app
    envVars:
      - key: SUPABASE_URL
        value: https://sdtnxvgofugmiouvchtf.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdG54dmdvZnVnbWlvdXZjaHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjAwMDQsImV4cCI6MjA2NTMzNjAwNH0.ulKFXnzm0HHaQ3pY_A-uToAUrNytyo7xaE42BV4D5kM
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: MODEL_PATH
        value: "model/best_cancer_model_small.h5"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: histoscan-data
      mountPath: /opt/render/project/src/model
      sizeGB: 1
    plan: standard # Use standard plan for more resources
